[package]
name = "m440"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs", package = "aidoku", features = ["json"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
strip = true
lto = true
